
[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
per-file-ignores = { "bank/__init__.py" = ["F401"] }

[tool.black]
line-length = 100
target-version = ["py311"]

