name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    uses: matheussiqueirahub/banco_aurora/.github/workflows/python-ci.yml@main
    with:
      matrix-os: '["ubuntu-latest"]'
      python-versions: '["3.11"]'
      run-lint: true
      run-tests: true
      coverage: false
